# Generated by Django 4.1.2 on 2022-10-16 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Полное наименование банка')),
                ('address', models.TextField(verbose_name='Aдрес Банка')),
                ('bank_number', models.CharField(max_length=100, verbose_name='Банковский идентификационный код')),
                ('settlement_account', models.CharField(max_length=100, verbose_name='Расчетный счет для оплаты')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Дополнительные сведения')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15, verbose_name='Тип счета')),
                ('status', models.CharField(choices=[('Выставлен', 'Выставлен'), ('Оплачен', 'Оплачен'), ('Отменен', 'Отменен')], default='Выставлен', max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 16, 16, 43, 1, 245940))),
                ('pay_to', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.company')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за одну единицу')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество продуктов или услуг')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.product')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Полное наименование предприятия')),
                ('taxes_number', models.CharField(max_length=100, verbose_name='Учетный номер плательщика')),
                ('address', models.TextField(verbose_name='Юридический адрес предприятия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон предприятия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email предприятия')),
                ('description', models.TextField(verbose_name='Описание предприятия')),
                ('bank_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.bankdetails')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.organization'),
        ),
    ]
