# Generated by Django 4.1.2 on 2022-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_organization_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Выставлен', 'Выставлен'), ('Оплачен', 'Оплачен'), ('Отменен', 'Отменен'), ('На проверке', 'На проверке')], default='Выставлен', max_length=100),
        ),
    ]
