# Generated by Django 4.1.2 on 2022-11-09 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_product_company'),
        ('bill', '0004_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Выставлен', 'Выставлен'), ('Оплачен', 'Оплачен'), ('Отменен', 'Отменен'), ('На проверке', 'На проверке')], default='На проверке', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.product'),
        ),
    ]
