# Generated by Django 4.1.2 on 2022-10-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Полное наименование банка')),
                ('address', models.TextField(verbose_name='Aдрес Банка')),
                ('bank_number', models.CharField(max_length=100, verbose_name='Банковский идентификационный код')),
                ('settlement_account', models.CharField(max_length=100, verbose_name='Расчетный счет для оплаты')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Дополнительные сведения')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='bank_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.bankdetails'),
        ),
    ]
