# Generated by Django 4.1.2 on 2022-10-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_bankdetails_company_bank_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.bankdetails'),
        ),
    ]
